version: "3.7"
services:
  database:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: mypassword
    container_name: db_app
    env_file:
      - .env-non-dev

  app:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: itpc_app
    ports:
      - 9990:8000
    depends_on:
      - database
